### ISSUE TITLE
dependencies的数据之间的连线颜色自定义

### ISSUE THREAD

**Issue by peter-yl** [ahwgs/react-gantt#17]
希望能实现dependencies的数据之间的连线颜色自定义，这样的话可以通过不同颜色的连线来确定不同的依赖路径

**Comment by ahwgs** [comment]
用v0.3.0版本，参考如图
<img width="601" alt="image" src="https://github.com/ahwgs/react-gantt/assets/26664586/783180ab-cd48-4f2b-83c2-cf4bf0eefbe8">
