### ISSUE TITLE
左侧table部分可隐藏

### ISSUE THREAD

**Issue by huyongtao-cmd** [ahwgs/react-gantt#18]
需求只需要右侧甘特图部分不需要左侧内容，希望能够支持单独显示右侧甘特图部分。
希望红色框内的全部隐藏。

<img width="693" alt="image" src="https://github.com/ahwgs/react-gantt/assets/71239740/e5c0e97b-94a3-4a11-8aab-49fa83632877">

**Comment by ahwgs** [comment]
@huyongtao-cmd  用v0.3.0版本吧
新增了 `hideTable` 字段。默认为 `false`
