### ISSUE TITLE
It's an amazing library. Just wanted to know if there is a way to translate the language to English for all the elements.

### ISSUE THREAD

**Issue by apurv-thakur** [ahwgs/react-gantt#8]

**Comment by nihei1206** [comment]
Hi, also I wanna do that same. then I try this way.

1. You can watch here, then chenge Chinese Lang to Your Lang , each points
~/node_modules/rc-gantt/dist/index.esm.js

2. Build ( npm run build ) 
3. success!

**Comment by apurv-thakur** [comment]
Thanks for the response, I did fork the library and did the changes.
Amazing work on the library though👍.

**Comment by ahwgs** [comment]
pnpm i rc-gantt@0.2.0

see：https://ahwgs.github.io/react-gantt/#/en-US/component
